# Generated by Django 5.2 on 2025-05-05 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="source_url",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="password",
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.TextField(default="https://example.com"),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.useraccount",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="password_hash",
            field=models.CharField(default="defaultpass123", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
